# Makefile for FocalTech Touchscreen driver

obj-$(CONFIG_TOUCHSCREEN_FTS) += fts_ts.o

fts_ts-y += focaltech_core.o
fts_ts-y += focaltech_ctl.o
fts_ts-y += focaltech_ex_fun.o
fts_ts-y += focaltech_flash.o
fts_ts-y += focaltech_gesture.o
fts_ts-y += focaltech_esd_protection.o
